version: '3'

services:
  butler:
    depends_on: 
    - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: butler
    ports: 
      - 8080:8080
    environment:
      - telegram.token=<your telegram token>
      - telegram.botName=<your bot name>
      - dialogflow.credentials.base64=<google credentials json in base64>
      - app.environment=<development|production>
      - spring.datasource.url=jdbc:postgresql://<postgresql host>:<postgresql port>/<postgresql database>
      - spring.datasource.username=<postgresql username>
      - spring.datasource.password=<postgresql password>
      - spring.jpa.hibernate.ddl-auto=update # in develoment auto run ddl 

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'butler'